from enum import Enum

class Difficulty(Enum):
    ROUTINE = 60
    VERY_EASY = 40
    EASY = 20
    AVERAGE = 0
    HARD = -20
    VERY_HARD = -40
    EXTREMELY_HARD = -60
    SHEER_FOLLY = -80
    ABSURD = -100

class Stats(Enum):
    STRENGTH = "STRENGTH"
    CONSTITUTION = "CONSTITUTION"
    INTELLIGENCE = "INTELLIGENCE"
    DEXTERITY = "DEXTERITY"
    PERCEPTION = "PERCEPTION"
    CHARISMA = "CHARISMA"
